services:
  certificate-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - CERT_DB_PATH=/app/data/certificates_db.json
      - ADMIN_TOKEN=your-secure-admin-token
