apiVersion: v1
kind: Service
metadata:
  labels:
    app: certificate-provider
  name: certificate-provider
  namespace: certificate-provider
spec:
  ports:
  - port: 8050
    protocol: TCP
    targetPort: 8050
  selector:
    app: certificate-provider
  type: LoadBalancer
