apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certificate-data
  namespace: certificate-provider
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
